getting this error
index.js:644 Uncaught ModuleBuildError: Module build failed (from ./node_modules/next/dist/build/webpack/loaders/next-swc-loader.js):
Error:   x Unknown regular expression flags.
   ,-[/home/user/studio/src/components/custom-logo.tsx:1:1]
 1 | / src/components/custom-logo.tsx
   : ^^^^^^^^^^^^^^^^
 2 | import React from 'react';
 3 |
 4 | interface CustomLogoProps extends React.SVGProps<SVGSVGElement> {}
   `----

Caused by:
    Syntax Error
    at processResult (/home/user/studio/no…undle5.js:29:407111)
    at <unknown> (/home/user/studio/no…undle5.js:29:408906)
    at <unknown> (/home/user/studio/no…derRunner.js:1:8645)
    at <unknown> (/home/user/studio/no…derRunner.js:1:5019)
    at r.callback (/home/user/studio/no…derRunner.js:1:4039)